### ISSUE TITLE
Implement pURLs on dependencies

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/dep-server#82]
# Background
After the investigation conducted in #42, it has become evident that the addition of pURLs to the dependency metadata on the dep-server would be a very useful piece of data to include.

1. Write an RFC for the addition of a pURL to the dep-server metadata
    - [x] paketo-buildpacks/dep-server/issues/83 
1. Add logic and automation to add the pURL to the each dependency
    - [x] paketo-buildpacks/dep-server/issues/84 
1. Update `jam update-dependencies` to include the pURL  
    - [x] paketo-buildpacks/packit/issues/204
